### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by derainbow** [bluedotiya/web_crawler#1] opened 2022-01-12 09:41 UTC
hey man,

![image](https://user-images.githubusercontent.com/18103104/149111421-a52c0fc1-8aa2-4f22-b572-786796347629.png)

what that issue mean ?

**Comment by bluedotiya** [comment] 2022-12-04 19:45
Hey @derainbow 
A bit with delay ;), i don't know the root cause of this issue but,
this seems to be a syntax error in Validator class.
As of right now Validator class in no longer in use so the bug is fixed by now

**Closed** 2023-01-21 23:41 UTC
